import type { ToolDefinition } from '../tools.js'

export const mcpOfficial: readonly ToolDefinition[] = [
  {
    name: 'filesystem',
    displayName: 'Filesystem',
    description: 'Secure file operations with configurable access controls',
    category: 'MCP — Official',
    type: 'mcp',
    source: 'npm:@modelcontextprotocol/server-filesystem',
    mcpConfig: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-filesystem'] },
  },
  {
    name: 'memory',
    displayName: 'Memory',
    description: 'Knowledge graph-based persistent memory system for LLMs',
    category: 'MCP — Official',
    type: 'mcp',
    source: 'npm:@modelcontextprotocol/server-memory',
    mcpConfig: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-memory'] },
  },
  {
    name: 'fetch',
    displayName: 'Fetch',
    description: 'Web content fetching and conversion for LLM usage',
    category: 'MCP — Official',
    type: 'mcp',
    source: 'npm:@modelcontextprotocol/server-fetch',
    mcpConfig: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-fetch'] },
  },
  {
    name: 'postgres',
    displayName: 'PostgreSQL',
    description: 'Read-only access to PostgreSQL databases via MCP',
    category: 'MCP — Official',
    type: 'mcp',
    source: 'npm:@modelcontextprotocol/server-postgres',
    mcpConfig: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-postgres'] },
    envVars: [{ key: 'DATABASE_URL', placeholder: '<your-postgres-connection-string>' }],
  },
  {
    name: 'sqlite',
    displayName: 'SQLite',
    description: 'MCP server for SQLite database operations',
    category: 'MCP — Official',
    type: 'mcp',
    source: 'npm:@modelcontextprotocol/server-sqlite',
    mcpConfig: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-sqlite'] },
  },
  {
    name: 'sequential-thinking',
    displayName: 'Sequential Thinking',
    description: 'Dynamic and reflective problem-solving through thought sequences',
    category: 'MCP — Official',
    type: 'mcp',
    source: 'npm:@modelcontextprotocol/server-sequential-thinking',
    mcpConfig: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-sequential-thinking'] },
  },
  {
    name: 'google-drive',
    displayName: 'Google Drive',
    description: 'Search and access Google Drive files via MCP',
    category: 'MCP — Official',
    type: 'mcp',
    source: 'npm:@modelcontextprotocol/server-gdrive',
    mcpConfig: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-gdrive'] },
  },
  {
    name: 'google-maps',
    displayName: 'Google Maps',
    description: 'Google Maps geocoding, directions, and places API via MCP',
    category: 'MCP — Official',
    type: 'mcp',
    source: 'npm:@modelcontextprotocol/server-google-maps',
    mcpConfig: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-google-maps'] },
    envVars: [{ key: 'GOOGLE_MAPS_API_KEY', placeholder: '<your-google-maps-key>' }],
  },
  {
    name: 'puppeteer',
    displayName: 'Puppeteer',
    description: 'Browser automation and web scraping via Puppeteer MCP',
    category: 'MCP — Official',
    type: 'mcp',
    source: 'npm:@modelcontextprotocol/server-puppeteer',
    mcpConfig: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-puppeteer'] },
  },
  {
    name: 'everart',
    displayName: 'EverArt',
    description: 'AI image generation via the EverArt platform',
    category: 'MCP — Official',
    type: 'mcp',
    source: 'npm:@modelcontextprotocol/server-everart',
    mcpConfig: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-everart'] },
    envVars: [{ key: 'EVERART_API_KEY', placeholder: '<your-everart-key>' }],
  },
  {
    name: 'git',
    displayName: 'Git',
    description: 'Read, search, and manipulate Git repositories via MCP',
    category: 'MCP — Official',
    type: 'mcp',
    source: 'npm:@modelcontextprotocol/server-git',
    mcpConfig: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-git'] },
  },
  {
    name: 'time',
    displayName: 'Time',
    description: 'Time and timezone conversion capabilities',
    category: 'MCP — Official',
    type: 'mcp',
    source: 'npm:@modelcontextprotocol/server-time',
    mcpConfig: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-time'] },
  },
  {
    name: 'everything',
    displayName: 'Everything',
    description: 'Reference MCP server for testing with prompts, resources, and tools',
    category: 'MCP — Official',
    type: 'mcp',
    source: 'npm:@modelcontextprotocol/server-everything',
    mcpConfig: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-everything'] },
  },
]
