import type { ToolDefinition } from '../tools.js'

export const mcpData: readonly ToolDefinition[] = [
  {
    name: 'mongodb',
    displayName: 'MongoDB',
    description: 'MongoDB document database — queries, aggregations, and CRUD',
    category: 'MCP — Databases',
    type: 'mcp',
    source: 'npm:mongodb-mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', 'mongodb-mcp-server'] },
    envVars: [{ key: 'MONGODB_URI', placeholder: '<your-mongodb-uri>' }],
  },
  {
    name: 'mysql',
    displayName: 'MySQL',
    description: 'MySQL relational database access via MCP',
    category: 'MCP — Databases',
    type: 'mcp',
    source: 'npm:mcp-server-mysql',
    mcpConfig: { command: 'npx', args: ['-y', 'mcp-server-mysql'] },
    envVars: [{ key: 'MYSQL_URL', placeholder: '<your-mysql-url>' }],
  },
  {
    name: 'redis',
    displayName: 'Redis',
    description: 'Redis in-memory data store — keys, hashes, and pub/sub',
    category: 'MCP — Databases',
    type: 'mcp',
    source: 'npm:mcp-server-redis',
    mcpConfig: { command: 'npx', args: ['-y', 'mcp-server-redis'] },
    envVars: [{ key: 'REDIS_URL', placeholder: '<your-redis-url>' }],
  },
  {
    name: 'elasticsearch',
    displayName: 'Elasticsearch',
    description: 'Elasticsearch — full-text search, analytics, and indexing',
    category: 'MCP — Databases',
    type: 'mcp',
    source: 'npm:mcp-server-elasticsearch',
    mcpConfig: { command: 'npx', args: ['-y', 'mcp-server-elasticsearch'] },
    envVars: [{ key: 'ELASTICSEARCH_URL', placeholder: '<your-elasticsearch-url>' }],
  },
  {
    name: 'clickhouse',
    displayName: 'ClickHouse',
    description: 'ClickHouse columnar database — fast analytics and OLAP queries',
    category: 'MCP — Databases',
    type: 'mcp',
    source: 'npm:@clickhouse/mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', '@clickhouse/mcp-server'] },
    envVars: [{ key: 'CLICKHOUSE_URL', placeholder: '<your-clickhouse-url>' }],
  },
  {
    name: 'snowflake',
    displayName: 'Snowflake',
    description: 'Snowflake cloud data warehouse — queries and data pipelines',
    category: 'MCP — Databases',
    type: 'mcp',
    source: 'npm:@snowflake/mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', '@snowflake/mcp-server'] },
    envVars: [
      { key: 'SNOWFLAKE_ACCOUNT', placeholder: '<your-snowflake-account>' },
      { key: 'SNOWFLAKE_USER', placeholder: '<your-snowflake-user>' },
    ],
  },
  {
    name: 'bigquery',
    displayName: 'BigQuery',
    description: 'Google BigQuery — serverless data warehouse and analytics',
    category: 'MCP — Databases',
    type: 'mcp',
    source: 'npm:@google-cloud/mcp-server-bigquery',
    mcpConfig: { command: 'npx', args: ['-y', '@google-cloud/mcp-server-bigquery'] },
    envVars: [
      { key: 'GOOGLE_APPLICATION_CREDENTIALS', placeholder: '<path-to-service-account.json>' },
    ],
  },
  {
    name: 'cockroachdb',
    displayName: 'CockroachDB',
    description: 'CockroachDB distributed SQL database via MCP',
    category: 'MCP — Databases',
    type: 'mcp',
    source: 'npm:cockroachdb-mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', 'cockroachdb-mcp-server'] },
    envVars: [{ key: 'DATABASE_URL', placeholder: '<your-cockroachdb-url>' }],
  },
  {
    name: 'airtable',
    displayName: 'Airtable',
    description: 'Airtable — spreadsheet-database hybrid for structured data',
    category: 'MCP — Databases',
    type: 'mcp',
    source: 'npm:airtable-mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', 'airtable-mcp-server'] },
    envVars: [{ key: 'AIRTABLE_API_KEY', placeholder: '<your-airtable-key>' }],
  },
  {
    name: 'fauna',
    displayName: 'Fauna',
    description: 'Fauna distributed document-relational database via MCP',
    category: 'MCP — Databases',
    type: 'mcp',
    source: 'npm:@fauna/mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', '@fauna/mcp-server'] },
    envVars: [{ key: 'FAUNA_SECRET', placeholder: '<your-fauna-secret>' }],
  },
  {
    name: 'dynamodb',
    displayName: 'DynamoDB',
    description: 'AWS DynamoDB — NoSQL key-value and document database',
    category: 'MCP — Databases',
    type: 'mcp',
    source: 'npm:@aws/mcp-server-dynamodb',
    mcpConfig: { command: 'npx', args: ['-y', '@aws/mcp-server-dynamodb'] },
    envVars: [
      { key: 'AWS_ACCESS_KEY_ID', placeholder: '<your-aws-access-key>' },
      { key: 'AWS_SECRET_ACCESS_KEY', placeholder: '<your-aws-secret-key>' },
    ],
  },
  {
    name: 'planetscale',
    displayName: 'PlanetScale',
    description: 'PlanetScale — serverless MySQL with branching and deploy requests',
    category: 'MCP — Databases',
    type: 'mcp',
    source: 'npm:@planetscale/mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', '@planetscale/mcp-server'] },
    envVars: [{ key: 'DATABASE_URL', placeholder: '<your-planetscale-url>' }],
  },
]
