import type { ToolDefinition } from '../tools.js'

export const mcpAi: readonly ToolDefinition[] = [
  {
    name: 'perplexity',
    displayName: 'Perplexity',
    description: 'Perplexity AI — real-time web research and answers via MCP',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:@perplexity-ai/mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', '@perplexity-ai/mcp-server'] },
    envVars: [{ key: 'PERPLEXITY_API_KEY', placeholder: '<your-perplexity-key>' }],
  },
  {
    name: 'e2b',
    displayName: 'E2B',
    description: 'E2B secure sandbox environments for code execution',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:@e2b/mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', '@e2b/mcp-server'] },
    envVars: [{ key: 'E2B_API_KEY', placeholder: '<your-e2b-key>' }],
  },
  {
    name: 'pinecone',
    displayName: 'Pinecone',
    description: 'Pinecone vector database — embeddings and similarity search',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:@pinecone-database/mcp',
    mcpConfig: { command: 'npx', args: ['-y', '@pinecone-database/mcp'] },
    envVars: [{ key: 'PINECONE_API_KEY', placeholder: '<your-pinecone-key>' }],
  },
  {
    name: 'exa',
    displayName: 'Exa',
    description: 'Exa neural search engine for finding relevant content',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:exa-mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', 'exa-mcp-server'] },
    envVars: [{ key: 'EXA_API_KEY', placeholder: '<your-exa-key>' }],
  },
  {
    name: 'tavily',
    displayName: 'Tavily',
    description: 'Tavily AI search engine optimized for LLM agents',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:tavily-mcp',
    mcpConfig: { command: 'npx', args: ['-y', 'tavily-mcp'] },
    envVars: [{ key: 'TAVILY_API_KEY', placeholder: '<your-tavily-key>' }],
  },
  {
    name: 'qdrant',
    displayName: 'Qdrant',
    description: 'Qdrant vector database — high-performance similarity search',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:@qdrant/mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', '@qdrant/mcp-server'] },
    envVars: [
      { key: 'QDRANT_URL', placeholder: '<your-qdrant-url>' },
      { key: 'QDRANT_API_KEY', placeholder: '<your-qdrant-key>' },
    ],
  },
  {
    name: 'weaviate',
    displayName: 'Weaviate',
    description: 'Weaviate vector database — semantic search and ML models',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:@weaviate/mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', '@weaviate/mcp-server'] },
    envVars: [{ key: 'WEAVIATE_URL', placeholder: '<your-weaviate-url>' }],
  },
  {
    name: 'langfuse',
    displayName: 'Langfuse',
    description: 'Langfuse LLM observability — traces, evals, and prompt management',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:@langfuse/mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', '@langfuse/mcp-server'] },
    envVars: [
      { key: 'LANGFUSE_PUBLIC_KEY', placeholder: '<your-langfuse-public-key>' },
      { key: 'LANGFUSE_SECRET_KEY', placeholder: '<your-langfuse-secret-key>' },
    ],
  },
  {
    name: 'ollama',
    displayName: 'Ollama',
    description: 'Ollama local LLM runner — manage and query local models',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:ollama-mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', 'ollama-mcp-server'] },
  },
  {
    name: 'huggingface',
    displayName: 'Hugging Face',
    description: 'Hugging Face models, datasets, and spaces via MCP',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:@huggingface/mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', '@huggingface/mcp-server'] },
    envVars: [{ key: 'HF_TOKEN', placeholder: '<your-huggingface-token>' }],
  },
  {
    name: 'cohere-mcp',
    displayName: 'Cohere MCP',
    description: 'Cohere AI models — text generation, embeddings, and reranking',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:@cohere/mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', '@cohere/mcp-server'] },
    envVars: [{ key: 'COHERE_API_KEY', placeholder: '<your-cohere-key>' }],
  },
  {
    name: 'deepseek',
    displayName: 'DeepSeek',
    description: 'DeepSeek AI models — code and reasoning via MCP',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:deepseek-mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', 'deepseek-mcp-server'] },
    envVars: [{ key: 'DEEPSEEK_API_KEY', placeholder: '<your-deepseek-key>' }],
  },
  {
    name: 'together',
    displayName: 'Together AI',
    description: 'Together AI — fast inference for open-source models',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:@together-ai/mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', '@together-ai/mcp-server'] },
    envVars: [{ key: 'TOGETHER_API_KEY', placeholder: '<your-together-key>' }],
  },
  {
    name: 'openrouter',
    displayName: 'OpenRouter',
    description: 'OpenRouter — unified API for 100+ LLM models',
    category: 'MCP — AI & ML',
    type: 'mcp',
    source: 'npm:openrouter-mcp-server',
    mcpConfig: { command: 'npx', args: ['-y', 'openrouter-mcp-server'] },
    envVars: [{ key: 'OPENROUTER_API_KEY', placeholder: '<your-openrouter-key>' }],
  },
]
