import type { ToolDefinition } from '../tools.js'

export const sdksPayments: readonly ToolDefinition[] = [
  {
    name: 'stripe-sdk',
    displayName: 'Stripe SDK',
    description: 'Stripe Node.js SDK — payments, subscriptions, and billing',
    category: 'SDKs — Payments & SaaS',
    type: 'sdk',
    source: 'npm:stripe',
    sdkPackage: 'stripe',
    envVars: [{ key: 'STRIPE_SECRET_KEY', placeholder: '<your-stripe-secret-key>' }],
    sdkTemplate: `import Stripe from 'stripe'\n\nexport const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!)\n`,
  },
  {
    name: 'twilio',
    displayName: 'Twilio',
    description: 'Twilio — SMS, voice, video, and communication APIs',
    category: 'SDKs — Payments & SaaS',
    type: 'sdk',
    source: 'npm:twilio',
    sdkPackage: 'twilio',
    envVars: [
      { key: 'TWILIO_ACCOUNT_SID', placeholder: '<your-twilio-sid>' },
      { key: 'TWILIO_AUTH_TOKEN', placeholder: '<your-twilio-token>' },
    ],
    sdkTemplate: `import twilio from 'twilio'\n\nexport const twilioClient = twilio(\n  process.env.TWILIO_ACCOUNT_SID!,\n  process.env.TWILIO_AUTH_TOKEN!,\n)\n`,
  },
  {
    name: 'sendgrid',
    displayName: 'SendGrid',
    description: 'SendGrid — transactional and marketing email delivery',
    category: 'SDKs — Payments & SaaS',
    type: 'sdk',
    source: 'npm:@sendgrid/mail',
    sdkPackage: '@sendgrid/mail',
    envVars: [{ key: 'SENDGRID_API_KEY', placeholder: '<your-sendgrid-key>' }],
    sdkTemplate: `import sgMail from '@sendgrid/mail'\n\nsgMail.setApiKey(process.env.SENDGRID_API_KEY!)\nexport { sgMail }\n`,
  },
  {
    name: 'postmark',
    displayName: 'Postmark',
    description: 'Postmark — reliable transactional email delivery',
    category: 'SDKs — Payments & SaaS',
    type: 'sdk',
    source: 'npm:postmark',
    sdkPackage: 'postmark',
    envVars: [{ key: 'POSTMARK_API_KEY', placeholder: '<your-postmark-key>' }],
    sdkTemplate: `import { ServerClient } from 'postmark'\n\nexport const postmark = new ServerClient(process.env.POSTMARK_API_KEY!)\n`,
  },
  {
    name: 'plaid',
    displayName: 'Plaid',
    description: 'Plaid — banking and financial data APIs',
    category: 'SDKs — Payments & SaaS',
    type: 'sdk',
    source: 'npm:plaid',
    sdkPackage: 'plaid',
    envVars: [
      { key: 'PLAID_CLIENT_ID', placeholder: '<your-plaid-client-id>' },
      { key: 'PLAID_SECRET', placeholder: '<your-plaid-secret>' },
    ],
    sdkTemplate: `import { PlaidApi, Configuration, PlaidEnvironments } from 'plaid'\n\nconst config = new Configuration({\n  basePath: PlaidEnvironments.sandbox,\n  baseOptions: { headers: { 'PLAID-CLIENT-ID': process.env.PLAID_CLIENT_ID!, 'PLAID-SECRET': process.env.PLAID_SECRET! } },\n})\nexport const plaid = new PlaidApi(config)\n`,
  },
  {
    name: 'square',
    displayName: 'Square',
    description: 'Square — payments, POS, and commerce platform',
    category: 'SDKs — Payments & SaaS',
    type: 'sdk',
    source: 'npm:square',
    sdkPackage: 'square',
    envVars: [{ key: 'SQUARE_ACCESS_TOKEN', placeholder: '<your-square-token>' }],
    sdkTemplate: `import { Client, Environment } from 'square'\n\nexport const square = new Client({ accessToken: process.env.SQUARE_ACCESS_TOKEN!, environment: Environment.Sandbox })\n`,
  },
  {
    name: 'lemonsqueezy',
    displayName: 'Lemon Squeezy',
    description: 'Lemon Squeezy — payments and subscriptions for digital products',
    category: 'SDKs — Payments & SaaS',
    type: 'sdk',
    source: 'npm:@lemonsqueezy/lemonsqueezy.js',
    sdkPackage: '@lemonsqueezy/lemonsqueezy.js',
    envVars: [{ key: 'LEMON_SQUEEZY_API_KEY', placeholder: '<your-lemonsqueezy-key>' }],
    sdkTemplate: `import { lemonSqueezySetup } from '@lemonsqueezy/lemonsqueezy.js'\n\nlemonSqueezySetup({ apiKey: process.env.LEMON_SQUEEZY_API_KEY! })\n`,
  },
  {
    name: 'paddle',
    displayName: 'Paddle',
    description: 'Paddle — billing, tax compliance, and subscription management',
    category: 'SDKs — Payments & SaaS',
    type: 'sdk',
    source: 'npm:@paddle/paddle-node-sdk',
    sdkPackage: '@paddle/paddle-node-sdk',
    envVars: [{ key: 'PADDLE_API_KEY', placeholder: '<your-paddle-key>' }],
    sdkTemplate: `import { Paddle } from '@paddle/paddle-node-sdk'\n\nexport const paddle = new Paddle(process.env.PADDLE_API_KEY!)\n`,
  },
]
