import type { ToolDefinition } from '../tools.js'

export const sdksAi: readonly ToolDefinition[] = [
  {
    name: 'anthropic',
    displayName: 'Anthropic',
    description: 'Anthropic Claude SDK — build with Claude models',
    category: 'SDKs — AI',
    type: 'sdk',
    source: 'npm:@anthropic-ai/sdk',
    sdkPackage: '@anthropic-ai/sdk',
    envVars: [{ key: 'ANTHROPIC_API_KEY', placeholder: '<your-anthropic-key>' }],
    sdkTemplate: `import Anthropic from '@anthropic-ai/sdk'\n\nexport const anthropic = new Anthropic()\n`,
  },
  {
    name: 'openai',
    displayName: 'OpenAI',
    description: 'OpenAI SDK — GPT, DALL-E, Whisper, and embeddings',
    category: 'SDKs — AI',
    type: 'sdk',
    source: 'npm:openai',
    sdkPackage: 'openai',
    envVars: [{ key: 'OPENAI_API_KEY', placeholder: '<your-openai-key>' }],
    sdkTemplate: `import OpenAI from 'openai'\n\nexport const openai = new OpenAI()\n`,
  },
  {
    name: 'google-ai',
    displayName: 'Google AI (Gemini)',
    description: 'Google Generative AI SDK — Gemini models and multimodal AI',
    category: 'SDKs — AI',
    type: 'sdk',
    source: 'npm:@google/generative-ai',
    sdkPackage: '@google/generative-ai',
    envVars: [{ key: 'GOOGLE_API_KEY', placeholder: '<your-google-ai-key>' }],
    sdkTemplate: `import { GoogleGenerativeAI } from '@google/generative-ai'\n\nexport const genAI = new GoogleGenerativeAI(process.env.GOOGLE_API_KEY!)\n`,
  },
  {
    name: 'vercel-ai',
    displayName: 'Vercel AI SDK',
    description: 'Vercel AI SDK — unified interface for LLM providers',
    category: 'SDKs — AI',
    type: 'sdk',
    source: 'npm:ai',
    sdkPackage: 'ai',
    sdkTemplate: `import { generateText } from 'ai'\n\nexport { generateText, streamText } from 'ai'\n`,
  },
  {
    name: 'mistral',
    displayName: 'Mistral',
    description: 'Mistral AI SDK — open-weight and commercial models',
    category: 'SDKs — AI',
    type: 'sdk',
    source: 'npm:@mistralai/mistralai',
    sdkPackage: '@mistralai/mistralai',
    envVars: [{ key: 'MISTRAL_API_KEY', placeholder: '<your-mistral-key>' }],
    sdkTemplate: `import { Mistral } from '@mistralai/mistralai'\n\nexport const mistral = new Mistral({ apiKey: process.env.MISTRAL_API_KEY! })\n`,
  },
  {
    name: 'groq',
    displayName: 'Groq',
    description: 'Groq SDK — ultra-fast LLM inference on LPU hardware',
    category: 'SDKs — AI',
    type: 'sdk',
    source: 'npm:groq-sdk',
    sdkPackage: 'groq-sdk',
    envVars: [{ key: 'GROQ_API_KEY', placeholder: '<your-groq-key>' }],
    sdkTemplate: `import Groq from 'groq-sdk'\n\nexport const groq = new Groq()\n`,
  },
  {
    name: 'langchain',
    displayName: 'LangChain',
    description: 'LangChain — framework for building LLM-powered applications',
    category: 'SDKs — AI',
    type: 'sdk',
    source: 'npm:langchain',
    sdkPackage: 'langchain',
    sdkTemplate: `import { ChatOpenAI } from 'langchain/chat_models/openai'\n\nexport const model = new ChatOpenAI()\n`,
  },
  {
    name: 'replicate',
    displayName: 'Replicate',
    description: 'Replicate — run open-source ML models in the cloud',
    category: 'SDKs — AI',
    type: 'sdk',
    source: 'npm:replicate',
    sdkPackage: 'replicate',
    envVars: [{ key: 'REPLICATE_API_TOKEN', placeholder: '<your-replicate-token>' }],
    sdkTemplate: `import Replicate from 'replicate'\n\nexport const replicate = new Replicate()\n`,
  },
  {
    name: 'cohere-sdk',
    displayName: 'Cohere SDK',
    description: 'Cohere SDK — text generation, embeddings, and reranking',
    category: 'SDKs — AI',
    type: 'sdk',
    source: 'npm:cohere-ai',
    sdkPackage: 'cohere-ai',
    envVars: [{ key: 'COHERE_API_KEY', placeholder: '<your-cohere-key>' }],
    sdkTemplate: `import { CohereClient } from 'cohere-ai'\n\nexport const cohere = new CohereClient({ token: process.env.COHERE_API_KEY! })\n`,
  },
  {
    name: 'fireworks',
    displayName: 'Fireworks AI',
    description: 'Fireworks AI — fast inference for open-source and fine-tuned models',
    category: 'SDKs — AI',
    type: 'sdk',
    source: 'npm:@fireworks-ai/sdk',
    sdkPackage: '@fireworks-ai/sdk',
    envVars: [{ key: 'FIREWORKS_API_KEY', placeholder: '<your-fireworks-key>' }],
    sdkTemplate: `import { Fireworks } from '@fireworks-ai/sdk'\n\nexport const fireworks = new Fireworks({ apiKey: process.env.FIREWORKS_API_KEY! })\n`,
  },
  {
    name: 'llamaindex',
    displayName: 'LlamaIndex',
    description: 'LlamaIndex — data framework for LLM applications with RAG',
    category: 'SDKs — AI',
    type: 'sdk',
    source: 'npm:llamaindex',
    sdkPackage: 'llamaindex',
    sdkTemplate: `import { VectorStoreIndex, SimpleDirectoryReader } from 'llamaindex'\n\nexport { VectorStoreIndex, SimpleDirectoryReader }\n`,
  },
  {
    name: 'ai-sdk-anthropic',
    displayName: 'AI SDK Anthropic Provider',
    description: 'Vercel AI SDK provider for Anthropic Claude models',
    category: 'SDKs — AI',
    type: 'sdk',
    source: 'npm:@ai-sdk/anthropic',
    sdkPackage: '@ai-sdk/anthropic',
    envVars: [{ key: 'ANTHROPIC_API_KEY', placeholder: '<your-anthropic-key>' }],
    sdkTemplate: `import { anthropic } from '@ai-sdk/anthropic'\n\nexport { anthropic }\n`,
  },
]
