import type { ToolDefinition } from '../tools.js'

export const sdksInfra: readonly ToolDefinition[] = [
  {
    name: 'upstash',
    displayName: 'Upstash Redis',
    description: 'Upstash serverless Redis — REST API for edge and serverless',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:@upstash/redis',
    sdkPackage: '@upstash/redis',
    envVars: [
      { key: 'UPSTASH_REDIS_REST_URL', placeholder: '<your-upstash-url>' },
      { key: 'UPSTASH_REDIS_REST_TOKEN', placeholder: '<your-upstash-token>' },
    ],
    sdkTemplate: `import { Redis } from '@upstash/redis'\n\nexport const redis = new Redis({\n  url: process.env.UPSTASH_REDIS_REST_URL!,\n  token: process.env.UPSTASH_REDIS_REST_TOKEN!,\n})\n`,
  },
  {
    name: 'inngest',
    displayName: 'Inngest',
    description: 'Inngest — durable functions, background jobs, and event-driven workflows',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:inngest',
    sdkPackage: 'inngest',
    sdkTemplate: `import { Inngest } from 'inngest'\n\nexport const inngest = new Inngest({ id: 'my-app' })\n`,
  },
  {
    name: 'resend',
    displayName: 'Resend',
    description: 'Resend — modern email API for developers',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:resend',
    sdkPackage: 'resend',
    envVars: [{ key: 'RESEND_API_KEY', placeholder: '<your-resend-key>' }],
    sdkTemplate: `import { Resend } from 'resend'\n\nexport const resend = new Resend(process.env.RESEND_API_KEY!)\n`,
  },
  {
    name: 'liveblocks',
    displayName: 'Liveblocks',
    description: 'Liveblocks — real-time collaboration infrastructure',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:@liveblocks/client',
    sdkPackage: '@liveblocks/client',
    sdkTemplate: `import { createClient } from '@liveblocks/client'\n\nexport const client = createClient({\n  publicApiKey: process.env.LIVEBLOCKS_PUBLIC_KEY!,\n})\n`,
  },
  {
    name: 'drizzle',
    displayName: 'Drizzle ORM',
    description: 'Drizzle ORM — lightweight TypeScript ORM with SQL-like syntax',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:drizzle-orm',
    sdkPackage: 'drizzle-orm',
    envVars: [{ key: 'DATABASE_URL', placeholder: '<your-database-url>' }],
    sdkTemplate: `import { drizzle } from 'drizzle-orm/node-postgres'\n\nexport const db = drizzle(process.env.DATABASE_URL!)\n`,
  },
  {
    name: 'prisma-client',
    displayName: 'Prisma Client',
    description: 'Prisma Client — auto-generated type-safe database client',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:@prisma/client',
    sdkPackage: '@prisma/client',
    envVars: [{ key: 'DATABASE_URL', placeholder: '<your-database-url>' }],
    sdkTemplate: `import { PrismaClient } from '@prisma/client'\n\nexport const prisma = new PrismaClient()\n`,
  },
  {
    name: 'kysely',
    displayName: 'Kysely',
    description: 'Kysely — type-safe SQL query builder for TypeScript',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:kysely',
    sdkPackage: 'kysely',
    envVars: [{ key: 'DATABASE_URL', placeholder: '<your-database-url>' }],
    sdkTemplate: `import { Kysely, PostgresDialect } from 'kysely'\nimport { Pool } from 'pg'\n\nexport const db = new Kysely({ dialect: new PostgresDialect({ pool: new Pool({ connectionString: process.env.DATABASE_URL! }) }) })\n`,
  },
  {
    name: 'trigger-dev',
    displayName: 'Trigger.dev',
    description: 'Trigger.dev — background jobs and long-running tasks for serverless',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:@trigger.dev/sdk',
    sdkPackage: '@trigger.dev/sdk',
    envVars: [{ key: 'TRIGGER_API_KEY', placeholder: '<your-trigger-key>' }],
    sdkTemplate: `import { TriggerClient } from '@trigger.dev/sdk'\n\nexport const client = new TriggerClient({ id: 'my-app', apiKey: process.env.TRIGGER_API_KEY! })\n`,
  },
  {
    name: 'hono',
    displayName: 'Hono',
    description: 'Hono — ultrafast web framework for the edge and serverless',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:hono',
    sdkPackage: 'hono',
    sdkTemplate: `import { Hono } from 'hono'\n\nexport const app = new Hono()\n`,
  },
  {
    name: 'trpc',
    displayName: 'tRPC',
    description: 'tRPC — end-to-end type-safe APIs without schemas or code generation',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:@trpc/server',
    sdkPackage: '@trpc/server',
    sdkTemplate: `import { initTRPC } from '@trpc/server'\n\nexport const t = initTRPC.create()\nexport const router = t.router\nexport const publicProcedure = t.procedure\n`,
  },
  {
    name: 'zod',
    displayName: 'Zod',
    description: 'Zod — TypeScript-first schema validation with static type inference',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:zod',
    sdkPackage: 'zod',
    sdkTemplate: `import { z } from 'zod'\n\nexport { z }\n`,
  },
  {
    name: 'uploadthing',
    displayName: 'UploadThing',
    description: 'UploadThing — file uploads for full-stack TypeScript apps',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:uploadthing',
    sdkPackage: 'uploadthing',
    envVars: [{ key: 'UPLOADTHING_SECRET', placeholder: '<your-uploadthing-secret>' }],
    sdkTemplate: `import { createUploadthing } from 'uploadthing/server'\n\nexport const f = createUploadthing()\n`,
  },
  {
    name: 'unkey',
    displayName: 'Unkey',
    description: 'Unkey — API key management and rate limiting',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:@unkey/api',
    sdkPackage: '@unkey/api',
    envVars: [{ key: 'UNKEY_ROOT_KEY', placeholder: '<your-unkey-root-key>' }],
    sdkTemplate: `import { Unkey } from '@unkey/api'\n\nexport const unkey = new Unkey({ rootKey: process.env.UNKEY_ROOT_KEY! })\n`,
  },
  {
    name: 'knock',
    displayName: 'Knock',
    description: 'Knock — notifications infrastructure for product teams',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:@knocklabs/node',
    sdkPackage: '@knocklabs/node',
    envVars: [{ key: 'KNOCK_API_KEY', placeholder: '<your-knock-key>' }],
    sdkTemplate: `import { Knock } from '@knocklabs/node'\n\nexport const knock = new Knock(process.env.KNOCK_API_KEY!)\n`,
  },
  {
    name: 'svix',
    displayName: 'Svix',
    description: 'Svix — webhooks as a service with delivery guarantees',
    category: 'SDKs — Infrastructure',
    type: 'sdk',
    source: 'npm:svix',
    sdkPackage: 'svix',
    envVars: [{ key: 'SVIX_API_KEY', placeholder: '<your-svix-key>' }],
    sdkTemplate: `import { Svix } from 'svix'\n\nexport const svix = new Svix(process.env.SVIX_API_KEY!)\n`,
  },
]
